var arrLang = {
    'en': {
        'menu_homeText': 'Home',
        'menu_aboutUs' : 'About us',
        'menu_topOffers' : 'Top Offers',
        'menu_blog' : 'Blog',
        'menu_meetUs': 'Meet us',
        'menu_login' : 'Login',
        'exclusive_affiliate' : 'Exclusive Affiliate Network',
        'for_crypto' : 'for Crypto Traffic',
        'created_by' : 'Created by a unique and powered-up team of professionals to provide you individual and best-performing solutions to monetize your traffic',
        'join_us' : 'Join us',
        'to_discover' : 'to discover the whole potential of our',
        'next-gen' : 'next-gen platform in the finance field',
        'unique' : 'Unique',
        'landing_pages' : 'landing pages',
        'support': 'Support',
        'payouts' : 'Payouts',
        'up_to' : 'up to',
        'immediate' : 'Immediate',
        'payouts' : 'payouts',
        'key_about' : 'About Us',
        'our_primary' : 'Our primary mission is to help our partners grow. To achieve the mission, we engage a target audience and build a strategy of communication. Being the long-term player in the affiliate         marketing industry, we analyze in detail every click and every conversion on a platform to create the most effective marketing flow. Our managers assist you non-stop to provide the highest level of support at any time.',
        'our_benefits' : 'Our benefits:',
        'highest_cpa' : 'Highest CPA',
        'crg_deals' : 'CRG deals',
        'exclusive_funnels' : 'Exclusive funnels',
        'smart_delivery' : 'Smart delivery algorithm',
        'transparent_CRM' : 'Transparent CRM',
        'top_offers' : 'TOP offers',
        'in_ourB' : 'In our blog you can find any information, including news and upcoming conferences in the finance and crypto field.',
        'crypto_vertical' : 'Crypto vertical: trending funnels and traffic sources',
        'cryptocurrency_and' : 'Cryptocurrency and brokers: regulated and unregulated',
        'how_to' : 'How to succeed in crypto vertical',
        'next' : 'Next',
        'contactUs' : 'Contact Us',
        'send' : 'Send',
        'register' : 'Register',
        'inOurB' : 'In our blog you can find any information, including news and upcoming conferences in the finance and crypto field.',
        'getInTouch' : 'GET IN TOUCH',
        'we_areHappy' : 'We are happy to help you if have you any additional questions.',
        'email' : 'Email us for any business inquiries.',
        'fillTheForm' : 'Fill the form if you have any useful information or a project you want to discuss with us.',
        'weWillReply' : 'We will reply to you to provide the most efficient solution.'
    },
    'ru': {

        'menu_homeText': 'Главная',
        'menu_aboutUs' : 'Про нас',
        'menu_topOffers' : 'Top Offers',
        'menu_blog' : 'Блог',
        'menu_meetUs': 'Встречайте нас',
        'menu_login' : 'Войти',
        'exclusive_affiliate' : 'Эксклюзивная Партнерская Сеть',
        'for_crypto' : 'для Крипто-Трафика',
        'created_by' : 'Создана уникальной и мощной командой профессионалов, чтобы предложить вам индивидуальные и наиболее эффективные решения для монетизации вашего трафика',
        'join_us' : 'Присоедениться',
        'to_discover' : 'и раскройте весь потенциал нашей',
        'next-gen' : 'платформы нового поколения в области финансов',
        'unique' : 'Уникальные',
        'landing_pages' : 'лендинги и воронки',
        'support': 'Поддержка',
        'payouts' : 'Выплаты ',
        'up_to' : 'до',
        'immediate' : 'Мгновенная',
        'payouts' : 'оплата',
        'key_about' : 'Про нас',
        'our_primary' : 'Proxicent - это платформа эффективного взаимодействия рекламодателей и их продуктов с источниками трафика, которые генерируют целевую аудиторию с высоким потенциалом LTV для продуктов. Наша основная миссия - клиентоориентированность и нацеленность на результат. Мы анализируем детально каждый клик и каждую конверсию на платформе, чтобы создать прибыльную связку как для рекламодателя, так и  для аффилиейта. Мы предоставляем каждому персональную поддержку высшего уровня - менеджеры Proxicent всегда доступны и готовы помочь.',
        'our_benefits' : 'Наши преимущества:',
        'highest_cpa' : 'Высокие CPA выплаты',
        'crg_deals' : 'CRG-сделки',
        'exclusive_funnels' : 'Высококачественные воронки и лендинги',
        'smart_delivery' : 'Новейший Smart алгоритм оптимизации крипто-трафика',
        'transparent_CRM' : 'Одна из лучших high-end платформ и CRM-система для отслеживания статистики в реальном времени',
        'top_offers' : 'TOP offers',
        'in_ourB' : 'В нашем блоге вы можете найти любую информацию, включая новости и предстоящие конференции в области финансов и криптовалюты.',
        'crypto_vertical' : 'Крипто-вертикаль: трендовые воронки и источники трафика',
        'cryptocurrency_and' : 'Криптовалюта и брокеры: регулируемые и нерегулируемые',
        'how_to' : 'Как добиться успеха в криптовалютной вертикали',
        'next' : 'Next',
        'contactUs' : 'Связаться с нами',
        'send' : 'Отправить',
        'register' : 'Регистрация',
        'inOurB' : 'В нашем блоге вы можете найти любую информацию, включая новости и предстоящие конференции в области финансов и криптовалют.',
        'getInTouch' : 'СВЯЗАТЬСЯ',
        'we_areHappy' : 'Мы будем рады помочь вам, если у вас возникнут дополнительные вопросы.',
        'email' : 'Напишите нам по любым бизнес вопросам.',
        'fillTheForm' : 'Заполните форму, если у вас есть полезная информация или проект, который вы хотите обсудить с нами.',
        'weWillReply' : 'Мы ответим вам и предложим наиболее эффективное решение.'
    }
};


$(function () {
    $('.translate').click(function () {
        var lang = $(this).attr('id');
        $('.lang').each(function (index, element) {
            $(this).text(arrLang[lang][$(this).attr('key')]);
        });
    });
});
